services:
  - type: web
    name: car-rental-chatbot
    env: python
    buildCommand: pip install -r requirements.txt && python database.py
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: OPENAI_API_KEY
        sync: false
