services:
  - type: web
    name: car-rental-chatbot
    runtime: python
    buildCommand: rm -f car_rental.db && pip install -r requirements.txt && python database.py
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: OPENAI_API_KEY
        sync: false
